<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Irene Rodríguez">

<title>Taller evaluado de repaso para el Primer Parcial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Taller_resuelto_files/libs/clipboard/clipboard.min.js"></script>
<script src="Taller_resuelto_files/libs/quarto-html/quarto.js"></script>
<script src="Taller_resuelto_files/libs/quarto-html/popper.min.js"></script>
<script src="Taller_resuelto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Taller_resuelto_files/libs/quarto-html/anchor.min.js"></script>
<link href="Taller_resuelto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Taller_resuelto_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Taller_resuelto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Taller_resuelto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Taller_resuelto_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link active" data-scroll-target="#objetivos">Objetivos</a></li>
  <li><a href="#descripción-de-los-datos" id="toc-descripción-de-los-datos" class="nav-link" data-scroll-target="#descripción-de-los-datos">Descripción de los datos</a></li>
  <li><a href="#análisis-descriptivo-e-interpretación-de-la-variancia" id="toc-análisis-descriptivo-e-interpretación-de-la-variancia" class="nav-link" data-scroll-target="#análisis-descriptivo-e-interpretación-de-la-variancia">Análisis descriptivo e interpretación de la variancia</a></li>
  <li><a href="#variables-no-cuantitativas-modelo-de-distribución-multinomial" id="toc-variables-no-cuantitativas-modelo-de-distribución-multinomial" class="nav-link" data-scroll-target="#variables-no-cuantitativas-modelo-de-distribución-multinomial">Variables no cuantitativas: Modelo de distribución multinomial</a></li>
  <li><a href="#cálculo-de-la-probabilidad-de-un-evento-en-una-muestra-de-tamaño-20" id="toc-cálculo-de-la-probabilidad-de-un-evento-en-una-muestra-de-tamaño-20" class="nav-link" data-scroll-target="#cálculo-de-la-probabilidad-de-un-evento-en-una-muestra-de-tamaño-20">Cálculo de la probabilidad de un evento en una muestra de tamaño 20:</a></li>
  <li><a href="#variables-cuantitativas-modelo-de-regresión-multivariante" id="toc-variables-cuantitativas-modelo-de-regresión-multivariante" class="nav-link" data-scroll-target="#variables-cuantitativas-modelo-de-regresión-multivariante">Variables cuantitativas: Modelo de regresión multivariante</a></li>
  <li><a href="#contraste-de-hipótesis-de-dos-medias-multivariante" id="toc-contraste-de-hipótesis-de-dos-medias-multivariante" class="nav-link" data-scroll-target="#contraste-de-hipótesis-de-dos-medias-multivariante">Contraste de hipótesis de dos medias multivariante</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  <li><a href="#recomendaciones" id="toc-recomendaciones" class="nav-link" data-scroll-target="#recomendaciones">Recomendaciones</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía">Bibliografía</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller evaluado de repaso para el Primer Parcial</h1>
<p class="subtitle lead">20582- Análisis de Datos para el GMAT</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Irene Rodríguez </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><a href="https://github.com/irn91/Taller-Repaso-AD">Enlace al repositorio de Github</a></p>
<p>Aplicamos los pasos del método científico para abordar, con datos simulados, un estudio relacionado con el turismo: los viajes realizados por la población que reside en España en el Segundo Trimestre del 2024. Estudiamos las relaciones entre los diferentes aspectos del viaje y las características de los viajeros.</p>
<p>Simulamos datos de una encuesta de turismo aplicada a los residentes de España sobre sus viajes en dicho periodo. Obtenemos información de la duración del viaje, el gasto por persona, el tiempo de transporte y el destino, entre otros aspectos de interés como el sexo, el rango de edad, los ingresos del hogar o la calificación global del viaje.</p>
<p>Planteamos objetivos de estudio, describimos los datos, los analizamos y obtenemos conclusiones.</p>
<section id="objetivos" class="level3">
<h3 class="anchored" data-anchor-id="objetivos">Objetivos</h3>
<p>La hipótesis general que deseamos investigar es “El gasto por persona y el tiempo de transporte no varían según el destino del viaje: España o el extranjero”.</p>
<p>Definimos objetivos específicos para validar o refutar dicha hipótesis.</p>
<ul>
<li><p>Breve análisis exploratorio de datos.</p></li>
<li><p>Modelar el destino del viaje por una distribución multinomial.</p></li>
<li><p>Realizar un modelo de regresión multivariante del gasto por persona en función de la duración del viaje y el tiempo de transporte.</p></li>
<li><p>Analizar si las medias del gasto por persona y el tiempo de transporte difieren significativamente según el destino del viaje.</p></li>
</ul>
</section>
<section id="descripción-de-los-datos" class="level3">
<h3 class="anchored" data-anchor-id="descripción-de-los-datos">Descripción de los datos</h3>
<p>Consultamos los resultados de la Encuesta de Turismo de Residentes del Segundo trimestre 2024 del repositorio <a href="https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&amp;cid=1254736176990&amp;menu=ultiDatos&amp;idp=1254735576863">INE</a>.</p>
<p>Algunos resultados de interés:</p>
<ul>
<li><p>El número de viajes de los residentes en España en el segundo trimestre es de más de 45 millones, el 68.8% de los residentes viaja.</p></li>
<li><p>El gasto total superó los 13.858 millones de euros.</p></li>
<li><p>La duración media del viaje es de 3.26 noches.</p></li>
<li><p>El gasto medio por persona es de 307.33 euros.</p></li>
<li><p>Entre los viajeros, el 51.8% son mujeres y el 48.2% hombres.</p></li>
<li><p>El 64.8% viaja solo por España, el 27.5% solo por elextranjero y el 7.7% por España y el extranjero.</p></li>
<li><p>Hay más viajeros jóvenes.</p></li>
<li><p>Hay más viajeros con mayores ingresos del hogar.</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="imagen1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Extracto de la Infografia de la encuesta del INE.</figcaption>
</figure>
</div>
<p>Definimos las variables clave:</p>
<ul>
<li><p>Variables cuantitativas:</p>
<ul>
<li><p><code>duracion_viaje</code>: duración del viaje en noches.</p></li>
<li><p><code>gasto_persona</code>: gasto por persona en euros.</p></li>
<li><p><code>tiempo_transporte</code>: tiempo dedicado al transporte durante el viaje en horas.</p></li>
<li><p><code>calificacion_viaje</code>: calificacion del viaje del 0 al 100.</p></li>
</ul></li>
<li><p>Variables ordinales:</p>
<ul>
<li><p><code>rango_edad</code>: rango de edad en años (“15-34”, “35-54”, “55 o más”).</p></li>
<li><p><code>ingresos_hogar</code>: ingresos del hogar en euros al mes (“1.499 o menos”, “1.500-3.499”, “3.500 o más”).</p></li>
<li><p><code>nivel_interes</code>: nivel de interés en el viaje (“Bajo”, “Neutro”, “Alto”).</p></li>
</ul></li>
<li><p>Variables nominales:</p>
<ul>
<li><p><code>destino</code>: ¿Por dónde viajan? “Solo España”, “España y extranjero”, “Solo extranjero”</p></li>
<li><p><code>sexo</code>: “Mujer”, “Hombre”.</p></li>
</ul></li>
</ul>
<p>Generamos una base de datos con 100 observaciones y las variables definidas. Las variables cuantitativas siguen una distribución normal multivariante. Utilizamos la información obtenida del INE para simular las medias y las proporciones.</p>
<p>Visualizamos la tabla de datos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 100
Columns: 9
$ duracion_viaje     &lt;dbl&gt; 3, 4, 6, 2, 5, 2, 4, 4, 2, 3, 4, 4, 6, 3, 1, 4, 2, …
$ tiempo_transporte  &lt;dbl&gt; 5, 5, 7, 4, 6, 3, 5, 6, 4, 5, 7, 6, 6, 3, 4, 6, 1, …
$ gasto_persona      &lt;dbl&gt; 325.54, 312.29, 314.59, 289.37, 281.46, 328.78, 305…
$ calificacion_viaje &lt;dbl&gt; 82, 75, 83, 77, 78, 81, 76, 82, 81, 80, 80, 81, 77,…
$ destino            &lt;fct&gt; solo ESP, solo ESP, ESP y extranjero, solo ESP, sol…
$ sexo               &lt;fct&gt; mujer, hombre, mujer, hombre, hombre, mujer, hombre…
$ rango_edad         &lt;ord&gt; 35-54, 15-34, 15-34, 35-54, 55 o más, 55 o más, 55 …
$ ingresos_hogar     &lt;ord&gt; 1.499 o menos, 1.499 o menos, 1.499 o menos, 1.500-…
$ nivel_interes      &lt;ord&gt; Bajo, Bajo, Bajo, Alto, Neutro, Bajo, Neutro, Neutr…</code></pre>
</div>
</div>
</section>
<section id="análisis-descriptivo-e-interpretación-de-la-variancia" class="level3">
<h3 class="anchored" data-anchor-id="análisis-descriptivo-e-interpretación-de-la-variancia">Análisis descriptivo e interpretación de la variancia</h3>
<p>Realicemos un análisis descriptivo multivariantes de la base de datos de acuerdo a los objetivos del trabajo.</p>
<section id="diferencias-por-sexo" class="level4">
<h4 class="anchored" data-anchor-id="diferencias-por-sexo">Diferencias por Sexo</h4>
<p>Veámoslo de froma más clara. Con <code>ggpais</code>, pintemos las variables cuantitativas por sexo.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Taller_resuelto_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el triangulo inferior de la representación vemos los gráficos de dispersión y en el triangulo superior se indican las correlaciones. Vemos que la correlación positiva entre la duración del viaje y el tiempo de transporte se muestra en su gráfico de dispersión: a mayor duración del viaje mayor tiempo de transporte.</p>
<p>En la diagonal se muestran las distribuciones de cada variable distinguidas por sexo. Vemos una cierta diferencia entre hombres y mujeres en la duración del viaje y tiempo de transporte.</p>
</section>
<section id="tiempo-de-transporte-por-sexo" class="level4">
<h4 class="anchored" data-anchor-id="tiempo-de-transporte-por-sexo">Tiempo de transporte por Sexo</h4>
<p>Cruzamos la variable cuantitativa <code>tiempo_transporte</code> con la variable categórica <code>sexo</code>. Usamos gráficos de <code>boxplot</code> para visualizar la información.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Taller_resuelto_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vemos que la mediana del tiempo que los hombres dedican al transporte en los viajes es mayor que la de las mujeres.</p>
</section>
<section id="duración-del-viaje-por-sexo-y-rango-de-edad" class="level4">
<h4 class="anchored" data-anchor-id="duración-del-viaje-por-sexo-y-rango-de-edad">Duración del viaje por Sexo y Rango de edad</h4>
<p>Ahora, graficamos un gráfico de violín para estudiar la duración del viaje por Sexo y Rango de edad.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Taller_resuelto_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La duración del viaje varía con el sexo y el rango de edad: A partir de los 35 años, la mediana de la duración del viaje en noches de los hombres es mayor que la de las mujeres y los viajes más largos corresponden a hombres de mayor edad.</p>
</section>
<section id="calificación-del-viaje-por-ingresos-del-hogar" class="level4">
<h4 class="anchored" data-anchor-id="calificación-del-viaje-por-ingresos-del-hogar">Calificación del viaje por ingresos del hogar</h4>
<p>Con <code>ggplot</code>, comparamos la calificación del viaje por ingresos del hogar.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Taller_resuelto_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notemos que la calificación del viaje varía según los ingresos del hogar. Los viajeros con mayor ingresos del hogar tienen una calificación mediana del viaje más baja. Por contra, los viajeros con ingresos del hogar de menos de 1.500 euros al mes han calificado de mediana el viaje más positivamente.</p>
<p>Es posible que los viajeros con mayores ingresos del hogar tengan expectativas más altas o viajes más costosos, influyendo en las calificaciones globales más bajas.</p>
</section>
<section id="variables-cuantitativas-varianza-generalizada-y-total" class="level4">
<h4 class="anchored" data-anchor-id="variables-cuantitativas-varianza-generalizada-y-total">Variables cuantitativas: varianza generalizada y total</h4>
<p>Para las variables cuantitativas de la base de datos, calculamos e interpretamos la información que proporciona la varianza generalizada y la varianza total.</p>
<p>Definición de varianza generalizada: <span class="math display">\[|S| = \prod_i^p \lambda_i\]</span></p>
<p>Definición de variación total: <span class="math display">\[Tr(S)= \sum_i^p \lambda_i\]</span></p>
<p>donde los <span class="math inline">\(\lambda_i\)</span> són los valores propios de la matriz de covarianzas <span class="math inline">\(S\)</span>.</p>
<p>Obtenemos los valores propios de <span class="math inline">\(S\)</span>.</p>
<p>La varianza generalizada es 14468.</p>
<p>de manera que hay mucha variabilidad conjunta.</p>
<p>Y la variación total es 226.</p>
<p>Por lo tanto, la suma de las variaciones es de 226.</p>
<p>Notemos que la cantidad de variabilidad que hay en el conjunto de datos es considerable.</p>
</section>
</section>
<section id="variables-no-cuantitativas-modelo-de-distribución-multinomial" class="level3">
<h3 class="anchored" data-anchor-id="variables-no-cuantitativas-modelo-de-distribución-multinomial">Variables no cuantitativas: Modelo de distribución multinomial</h3>
<p>Seleccionamos una de las variables no cuantitativas: <code>destino</code>. La varible <code>destino</code> es el factor que indica por dónde viaja la persona. Tiene tres niveles: sólo por España (<code>solo ESP</code>), por España y el extranjero (<code>ESP y extranjero</code>) y sólo por el extranjero (<code>solo extranjero</code>).</p>
<p>La modelizamos con una distribución multinomial, debemos estimar sus parámetros.</p>
<p>De las 100 observaciones:</p>
<ul>
<li><p>Solo por España (<code>solo ESP</code>) tiene 65 observaciones: frecuencia relativa <span class="math inline">\(p_1 = 0.65\)</span>.</p></li>
<li><p>Solo por elextranjero (<code>solo extranjero</code>) tiene 27 observaciones: frecuencia relativa <span class="math inline">\(p_{2} = 0.27\)</span>.</p></li>
<li><p>Por España y el extranjero (<code>ESP y extranjero</code> tiene 8 observaciones: frecuencia relativa <span class="math inline">\(p_{3} = 0.08\)</span>.</p></li>
</ul>
<p>Distribución multinomial de parámetros estimados <span class="math inline">\(p_1 = 0.65\)</span>, <span class="math inline">\(p_{2} = 0.27\)</span> y <span class="math inline">\(p_{3} = 0.08\)</span>.</p>
</section>
<section id="cálculo-de-la-probabilidad-de-un-evento-en-una-muestra-de-tamaño-20" class="level3">
<h3 class="anchored" data-anchor-id="cálculo-de-la-probabilidad-de-un-evento-en-una-muestra-de-tamaño-20">Cálculo de la probabilidad de un evento en una muestra de tamaño 20:</h3>
<p>Utilizamos el modelo para calcular la probabilidad de que ocurra un evento de interés en una muestra de tamaño 20, relevante para el problema.</p>
<p>Interesa saber si la mayoría viaja por España. De una muestra de tamaño 20, queremos calcular la probabilidad de que haya 15 observaciones de <code>solo ESP</code>, 3 de <code>solo extranjero</code> y 2 de <code>ESP y extranjero</code>.</p>
<p>Como consideramos una distribución multinomial:</p>
<p><span class="math display">\[
P(X_1 = x_1, X_2 = x_2, X_3 = x_3) = \frac{20!}{x_1! x_2! x_3!} \cdot p_1^{x_1} \cdot p_2^{x_2} \cdot p_3^{x_3}
\]</span></p>
<p>Donde <span class="math inline">\(x_1 = 15\)</span>, <span class="math inline">\(x_2 = 3\)</span>, <span class="math inline">\(x_3 = 2\)</span>, <span class="math inline">\(p_1 = 0.65\)</span>, <span class="math inline">\(p_2 = 0.27\)</span>, <span class="math inline">\(p_3 = 0.08\)</span>.</p>
<p>Así, la probabilidad es del 3.05%.</p>
<p>Con la función <code>dmultinom</code> de <code>R</code> obtenemos el mismo valor.</p>
</section>
<section id="variables-cuantitativas-modelo-de-regresión-multivariante" class="level3">
<h3 class="anchored" data-anchor-id="variables-cuantitativas-modelo-de-regresión-multivariante">Variables cuantitativas: Modelo de regresión multivariante</h3>
<p>Con las variables cuantitativas de tu base de datos, ajusta un modelo de regresión multivariante en la forma:</p>
<p><span class="math display">\[Y=\beta_0+\beta_1 X_1+ \cdots + \beta_p X_p + \epsilon\]</span> Donde <span class="math inline">\(Y\)</span> es la variable cuantitativa que deseas explicar en función del resto de variables cuantitativas registradas. Además, calcula la función de score e interpreta su resultado en el contexto del problema.</p>
<p>Vamos a modelar <code>gasto_persona</code> como función de las demás variables cuantitativas: <code>tiempo_transporte</code>, <code>duracion_viaje</code> y <code>calificacion_viaje</code>.</p>
<p>Usamos <code>lm</code> para ajustar el modelo de regresión múltiple, que es una forma de regresión multivariante. Es de la forma:</p>
<p>gasto_persona = <span class="math inline">\(\beta_0 + \beta_1 *\)</span> tiempo_transporte <span class="math inline">\(+ \beta_2 *\)</span> duracion_viaje <span class="math inline">\(+ \beta_3*\)</span>calificacion_viaje <span class="math inline">\(+ \epsilon\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gasto_persona ~ tiempo_transporte + duracion_viaje + 
    calificacion_viaje, data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-39.240  -7.821  -0.229   9.152  30.450 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        285.1231    23.7144  12.023  &lt; 2e-16 ***
tiempo_transporte   -2.4370     0.9263  -2.631  0.00992 ** 
duracion_viaje       4.6636     1.2490   3.734  0.00032 ***
calificacion_viaje   0.2581     0.3091   0.835  0.40573    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 14.09 on 96 degrees of freedom
Multiple R-squared:  0.1401,    Adjusted R-squared:  0.1132 
F-statistic: 5.212 on 3 and 96 DF,  p-value: 0.002234</code></pre>
</div>
</div>
<p>Notemos que los p-valores nos indican para cada coeficiente si la variable independiente tiene un efecto significativo en <code>gasto_persona</code>. Un p-valor menor a 0.05 sugiere que la variable tiene un efecto significativo. Por ello, tanto el término independiente como los coeficientes de <code>tiempo_transporte</code> y <code>duracion_viaje</code> tienen un efecto significativos. Por contra, la calificacion del viaje no tiene un efecto significativo en el gasto. Por lo tanto, lo obviamos.</p>
<p>Es interesante que la calificación del viaje no tenga un efecto significativo en el gasto. Podría indicar que los gastos del vaijero no dependen necesariamente de su satisfacción con el viaje, sino del tipo de viaje o destino.</p>
<p>Consideremos el modelo de regresión multivariante siguiente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gasto_persona ~ tiempo_transporte + duracion_viaje, 
    data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-36.981  -7.727  -0.293   9.213  29.610 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       304.6792     3.7369  81.532  &lt; 2e-16 ***
tiempo_transporte  -2.3708     0.9215  -2.573 0.011601 *  
duracion_viaje      4.7910     1.2377   3.871 0.000197 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 14.07 on 97 degrees of freedom
Multiple R-squared:  0.1338,    Adjusted R-squared:  0.116 
F-statistic: 7.493 on 2 and 97 DF,  p-value: 0.0009422</code></pre>
</div>
</div>
<p>Ahora todos los coeficientes tienen un efecto significativo. <code>Adjusted R-squared</code> es de 0.116.</p>
<p>Consideramos que <code>gasto_persona</code> sigue un modelo de regresión multivariante del tipo:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1X_1 + \beta_2X_2  + \epsilon
\]</span></p>
<p>Donde <span class="math inline">\(Y\)</span> es <code>gasto_persona</code>, <span class="math inline">\(X_1\)</span> es <code>tiempo_transporte</code>, <span class="math inline">\(X_2\)</span> es <code>duracion_viaje</code> y <span class="math inline">\(\epsilon\)</span> es el término de error.</p>
<p>Calculamos la función de score e interpretamos el resultado. Es una forma de estudiar si el modelo está bien ajustado. Seguimos las indicaciones de la resolución del Problema 2 de la Práctica 5 de la asignatura.</p>
<p>Para calcular la función de score, consideramos que queremos estimar los parámetros <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span> y <span class="math inline">\(\beta_2\)</span> del modelo de regresión lineal múltiple: <span class="math inline">\(Y = \beta_0 + \beta_1*X_1 + \beta_2*X_2  + \epsilon\)</span>.</p>
<p>Necesitamos derivar la función de verosimilitud en términos de estos parámetros y luego obtener la función de score tomando la derivada de la log-verosimilitud con respector a <span class="math inline">\(\beta\)</span>.</p>
<p>Podemos escribir el modelo en forma matricial como:</p>
<p><span class="math display">\[
Y = X \beta + \epsilon
\]</span> donde</p>
<ul>
<li><p><span class="math inline">\(X = (1 \, X_1 \, X_2)\)</span> es una columna de unos seguida de las columnas formadas por <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span>.</p></li>
<li><p><span class="math inline">\(\beta = (\beta_0, \beta_1, \beta_2)^t\)</span></p></li>
<li><p><span class="math inline">\(\epsilon \sim  \mathcal{N} (0, \sigma^2I)\)</span> es el vector de términos de error, con una distribución normal con media 0 y varianza <span class="math inline">\(\sigma^2\)</span>.</p></li>
</ul>
<p>Como el término del error <span class="math inline">\(\epsilon\)</span> sigue una normal, el vector <span class="math inline">\(Y\)</span> también sigue una distribución normal, con media <span class="math inline">\(X\beta\)</span> t varianza <span class="math inline">\(\sigma^2I\)</span>.</p>
<p><span class="math display">\[
Y \sim  \mathcal{N} (X\beta, \sigma^2I)
\]</span></p>
<p>Así, la función de densidad conjunta de <span class="math inline">\(Y\)</span> es:</p>
<p><span class="math display">\[
f(Y|\beta,\sigma^2) = \frac{1}{(2\pi\sigma^2)^{\frac{n}{2}}}exp \left( -\frac{1}{2\sigma^2}(Y-X\beta)^T(Y-X\beta) \right)
\]</span> La log-verosimilitud <span class="math inline">\(\ell(\beta,\sigma^2|Y)\)</span> es:</p>
<p><span class="math display">\[
\ell(\beta,\sigma^2|Y) = - \frac{n}{2} \log(2\pi\sigma^2) - \frac{1}{2\sigma^2}(Y-X\beta)^T(Y-X\beta)
\]</span> La función de score es el gradiente de la log-verosimilitud respecto a los parámetros que nos interesan. Hacemos la derivada parcial con respecto a <span class="math inline">\(\beta\)</span> obteniendo la función de Score en términos de <span class="math inline">\(\beta\)</span>.</p>
<p><span class="math display">\[
\text{Score}(\beta) = \frac {\partial \ell}{\partial \beta}= \frac{1}{\sigma^2}X^T(Y-X\beta)
\]</span> La función de <span class="math inline">\(Score(\beta)\)</span> nos indica cómo varía la verosimilitud del modelo según los parámetros <span class="math inline">\(\beta\)</span>. Si la función de Score es 0, el modelo alcanza un máximo de verosimiltud respecto <span class="math inline">\(\beta\)</span> así que tenemos un buen ajuste de los coeficientes <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span> y <span class="math inline">\(\beta_2\)</span>. Si no es 0, podríamos seguir cambiando los valores de <span class="math inline">\(\beta\)</span> para un encontrar un mejor ajute.</p>
<p>Calculamos el valor de la función de score para estos datos. Usamos los valores de nuestro modelo ajustado:</p>
<ul>
<li><span class="math inline">\(\hat \beta_0 = 304.6792\)</span> (<code>Intercept</code>)</li>
<li><span class="math inline">\(\hat \beta_1=-2.3708\)</span> (<code>tiempo_transporte</code>)</li>
<li><span class="math inline">\(\hat \beta_2=4.7910\)</span> (<code>duracion_viaje</code>)</li>
</ul>
<p>Obtenemos el siguiente resultado:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                          [,1]
(Intercept)       1.464154e-14
tiempo_transporte 7.033681e-14
duracion_viaje    4.392462e-14</code></pre>
</div>
</div>
<p>Los valores de Score que obtenemos son cercanos a cero. Esto sugiere que el modelo está bien ajustado (se encuentra cerca del punto de máxima verosimilitud respecto a los parámetros) y no sería necesario realizar ajustes adicionales.</p>
</section>
<section id="contraste-de-hipótesis-de-dos-medias-multivariante" class="level3">
<h3 class="anchored" data-anchor-id="contraste-de-hipótesis-de-dos-medias-multivariante">Contraste de hipótesis de dos medias multivariante</h3>
<p>Realizamos un contraste de hipótesis de dos medias multivariante relevante para el problema.</p>
<p>Evaluamos si el vector de medias de las variables cuantitativas de interés <code>gasto_persona</code> y <code>tiempo_transporte</code> es el mismo para dos niveles distintos de la variable no cuantitativa <code>destino</code> que hemos modelado como multinomial: viaje solo por España (<code>solo ESP</code>) y viaje solo por el estrangero (<code>solo extranjero</code>).</p>
<p>Por una parte, ejecutamos el constraste de forma teórica.</p>
<p>Consultamos la sección <em>3.4.2. Test sobre la media: dos poblaciones</em> de los apuntes de la asignatura.</p>
<p>Supongamos que tenemmos dos matrices de datos independientes <span class="math inline">\(X_{n_1\times p}\)</span>, <span class="math inline">\(Y_{n_2\times p}\)</span> que provienenn de distribuciones <span class="math inline">\(N_p(\mu_1, \Sigma), N_p(\mu_2, \Sigma)\)</span>.</p>
<p>En nuestro caso, - <span class="math inline">\(p=2\)</span> - <span class="math inline">\(X\)</span> el subconjunto de <code>gasto_persona</code> y <code>tiempo_transporte</code> cuyo destino es <code>solo ESP</code>, <span class="math inline">\(n_1 = 65\)</span> el tamaño de la muestra <span class="math inline">\(X\)</span>. - <span class="math inline">\(Y\)</span> el subconjuto de <code>gasto_persona</code> y <code>tiempo_transporte</code> cuyo destino es <code>solo extranjero</code>, <span class="math inline">\(n_2 = 27\)</span> el tamaño de la muestra <span class="math inline">\(X\)</span>.</p>
<p>Construimos un test sobre la hipótesis</p>
<p><span class="math display">\[
H_0: \mu_1 = \mu_2
\]</span> Como <span class="math inline">\(\Sigma\)</span> es desconocida, el estadístico de contraste es</p>
<p><span class="math display">\[
\frac{n_1+n_2-1-p}{(n_1+n_2-2)p}\frac{n_1n_2}{n_1+n_2}(\overline{\mathbf{x}}-\overline{\mathbf{y}})'\widehat{\mathbf{S}}^{-1}(\overline{\mathbf{x}}-\overline{\mathbf{y}})\sim F^p_{n_1+n_2-1-p}.
\]</span> Siendo <span class="math inline">\(\widehat{\mathbf{S}}=(n_1\mathbf{S}_1+n_2\mathbf{S}_2)/(n_1+n_2-2)\)</span> la estimación centrada (insesgada) de <span class="math inline">\(\Sigma\)</span>.</p>
<p>Calculamos las medias muestrales (<span class="math inline">\(\over{x}\)</span>, <span class="math inline">\(\over{y}\)</span>), las matrices de covariancia muestrales (<span class="math inline">\(S_1\)</span>, <span class="math inline">\(S_2\)</span>) y la matriz <span class="math inline">\(\hat{S}\)</span>.</p>
<p>Obtenemos el estadístico de contraste <span class="math inline">\(F^p_{n_1+n_2-1-p}\)</span> y lo comparamos con el valor crítico (usando un nivel de signifiación <span class="math inline">\(\alpha = 0.05\)</span>) para decidir si rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p>Si el estadístico de contraste es mayor al valor crítico, rechazamos <span class="math inline">\(H_0\)</span>: las medias son diferentes para los dos destinos.</p>
<p>Si el estadístico de constraste no alcanza el valor crítico, no rechazamos la hipótesis nula.</p>
<p>Como el valor del estadístico de contraste (0.106) no alcanza el valor crítico (3.099), no rechazamos <span class="math inline">\(H_0\)</span>. No tenemos suficiente evidencia para afirmar que las medias de <code>gasto_persona</code> y <code>tiempo_transporte</code> son significativamente diferentes entre los destinos.</p>
<p>Por otra parte, ejecutamos el contraste con la función <code>hostelling.test</code>de <code>R</code>.</p>
<p>Evaluamos si el vector de medias de las variablescuantitativa <code>gasto_persona</code> y <code>tiempo_transporte</code> es el mismo para dos niveles distintos de la variable no cuantitativa <code>destino</code> que hemos modelado como multinomial: viaje solo por España (<code>solo ESP</code>) y viaje solo por el estrangero (<code>solo extranjero</code>).</p>
<p>El p-valor del test de Hotelling es de 0.8995, mayor al nivel de significancia estánrd <span class="math inline">\(\alpha = 0.05\)</span>. No hay evidencia suficiente para rechazar la hipótesis nula de que las medias multivariantes de los dos grupos son iguales. En conclusión, las diferencias entre los dos grupos no son estadísticamente significativas.</p>
<p>No podemos concluir que las medias de <code>gasto_persona</code>y <code>tiempo_transporte</code> difieran significativamente entre los viajeros que van sólo por España y los que viajan solo por el extranjero, las diferencias entre los dos grupos no son estadísticamente significativas.</p>
</section>
<section id="conclusiones" class="level3">
<h3 class="anchored" data-anchor-id="conclusiones">Conclusiones</h3>
<p>En conclusión, recogemos los resultados de interés de los análisis y valoramos si apoyan o refutan la hipótesis general.</p>
<p>Del Análisis Descriptivo, destacamos:</p>
<ul>
<li><p>A mayor duración del viaje en noches mayor tiempo de transporte en horas, lo cual es razonable.</p></li>
<li><p>La duración del viaje varía con el sexo y el rango de edad: A partir de los 35 años, la mediana de la duración del viaje en noches de los hombres es mayor que la de las mujeres, y los viajes más largos corresponden principalmente a hombres de mayor edad.</p></li>
<li><p>Los viajeros con mayor ingresos del hogar tienen una calificación mediana del viaje más baja. Es posible que los viajeros con mayores ingresos del hogar tengan expectativas más altas o viajes más costosos, influyendo en las calificaciones globales más bajas.</p></li>
</ul>
<p>Hemos modelado el destino de viaje por una multinomial. Esto puede ser útil para predecir el comportamiento de los viajeros.</p>
<p>Hemos obtenido un modelo de regresión multivariante de la forma:</p>
<p>gasto_persona = <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span> tiempo_transporte + <span class="math inline">\(\beta_2\)</span> duracion_viaje</p>
<p>Considermaos que este modelo está bien ajustado (los valores de Score que obtenemos son cercanos a cero).</p>
<p>Hemos visto que no podemos concluir que las medias del gasto por persona y el tiempo de transporte difieran significativamente entre los viajeros que viajan sólo por España y los que viajan solo por el extranjero.</p>
<p>Esto apoya la hipótesis general de que el gasto por persona y el tiempo de transporte no varían según el destino del viaje: España o el extranjero.</p>
</section>
<section id="recomendaciones" class="level3">
<h3 class="anchored" data-anchor-id="recomendaciones">Recomendaciones</h3>
<p>Consideramos sugerencias para futuros estudios o para poíticas de turismo.</p>
<p>Para futuros estudios, proponemos recoger información sobre el tipo de alojamiento y estudiar su relación con la calificación global y el gasto. También puede ser interesante comparar los datos entre diferentes trimestres y obersvar la estacionalidad.</p>
<p>Para políticas de turismo, proponemos adaptar la oferta a las expecativas de viajeros de altos ingresos, dado que estos viajeros tienden a dar calificaciones más bajas. Por ejemplo, ampliar la variedad de servicios premium.</p>
</section>
<section id="bibliografía" class="level3">
<h3 class="anchored" data-anchor-id="bibliografía">Bibliografía</h3>
<ul>
<li><p><a href="https://aprender-uib.github.io/AD/">Apuntes de la Asignatura</a>.</p></li>
<li><p>Ejercicios resuletos de la Asignatura.</p></li>
<li><p>Documento “Recomendaciones para escribir informes de proyectos en Estadística” del curso.</p></li>
<li><p><a href="https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&amp;cid=1254736176990&amp;menu=ultiDatos&amp;idp=1254735576863">Encuesta de Turismo de Residentes del Segundo trimestre 2024</a> del repositorio del INE</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>